#!/usr/bin/env python3
"""Bill of materials, print packages and checksums.

    python3 outputs/muju-physical-set-v1/cad/package.py

Per-part mass and cost figures are ESTIMATES from exported solid volume; per-variant
slicer totals come from validation/slicer/ when cad/slice_check.py has been run.
"""
from __future__ import annotations

import csv
import hashlib
import json
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent
MAN = json.loads((OUT / "manifest.json").read_text())
P = json.loads((HERE / "params.json").read_text())

DENSITY = {"crystal": 1.27}  # PETG; everything else PLA 1.24 g/cm3 (typical datasheet)
FILL = 0.80  # assumed effective fill: small parts at 3 walls + 15-20 % infill are mostly shell (assumption)
_SL = OUT / "validation" / "slicer" / "slicer-checks.json"
SLICE_DOC = json.loads(_SL.read_text()) if _SL.exists() else {"meta": {}, "plates": []}
SLICE, SLICE_META = SLICE_DOC["plates"], SLICE_DOC["meta"]
PRICE_PER_KG_ASSUMED = 20.0  # USD, placeholder -- store prices were NOT verified (research/filament-shortlist.md)
SPOOL_KG = 1.0


def material(color):
    return "PETG" if color == "crystal" else "PLA"


def sha(p: Path):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def bom():
    rows = []
    for p in MAN["parts"]:
        for inst in p["instances"]:
            vol = p["geometry"]["brep_volume_mm3"] / 1000.0
            dens = DENSITY.get(inst["color"], 1.24)
            rows.append({
                "variant": p["variant"], "production": p["production"], "part_id": p["id"], "family": p["family"],
                "color": inst["color"], "material": material(inst["color"]), "filament_lead": inst["filament_lead"],
                "qty": inst["qty_per_set"], "bbox_mm": "x".join(f"{v:.1f}" for v in p["geometry"]["bbox_mm"]),
                "solid_volume_cm3_each": round(vol, 3),
                "est_mass_g_each": round(vol * dens * FILL, 2),
                "est_mass_g_total": round(vol * dens * FILL * inst["qty_per_set"], 1),
                "stl": p["geometry"]["stl"],
            })
    return rows


def main():
    rows = bom()
    pr = OUT / "print"
    pr.mkdir(exist_ok=True)
    with open(pr / "BOM.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)
    lines = ["# Bill of materials", "",
             "Generated by `cad/package.py` from `manifest.json`. **Quantities are exact; masses and costs are estimates.**", "",
             "Per-part masses below are volume estimates; the slicer totals per variant (Bambu Studio, H2C profile) follow each table.", "",
             "Assumptions for the per-part estimates:",
             f"- Mass = exported solid volume × density (PLA 1.24, PETG 1.27 g/cm³) × **{FILL:.0%} effective fill** (assumed).",
             "- Purge, support, brim and failed-print waste are **not** included; single-colour plates need no purge tower.",
             f"- Cost uses a **placeholder {PRICE_PER_KG_ASSUMED:.0f} USD/kg**, not a verified store price. Bambu store pages were blocked",
             "  during research (see `research/filament-shortlist.md`), so no price is quoted as current.",
             "- Print time and sliced mass come from `validation/slicer/slicer-checks.json` (`cad/slice_check.py`)." if SLICE else
             "- Print time: **not estimated**. Run `cad/slice_check.py` (Bambu Studio, H2C profile) to obtain it.", ""]
    for v in ("facet", "pebble", "turned"):
        vr = [r for r in rows if r["production"] and r["variant"] in (v, "shared")]
        tot = sum(r["qty"] for r in vr)
        lines += [f"## {P['variants'][v]['name']} (`{v}`) — {tot} printed objects", "",
                  "| Colour / material | Filament lead | Part | Qty | Est. g each | Est. g total |", "|---|---|---|---:|---:|---:|"]
        by = {}
        for r in sorted(vr, key=lambda r: (r["color"], r["part_id"])):
            lines.append(f"| {r['color']} ({r['material']}) | {r['filament_lead']} | `{r['part_id']}` | {r['qty']} | {r['est_mass_g_each']} | {r['est_mass_g_total']} |")
            by.setdefault(r["color"], [0, 0.0])
            by[r["color"]][0] += r["qty"]
            by[r["color"]][1] += r["est_mass_g_total"]
        lines += ["", "| Colour | Objects | Est. consumed g | Est. consumed cost (placeholder price) | Whole 1 kg spools to buy |", "|---|---:|---:|---:|---:|"]
        tg = tc = 0
        for c, (n, g) in sorted(by.items()):
            spools = max(1, -(-g // (SPOOL_KG * 1000 * 0.9)))  # keep 10 % margin per spool
            lines.append(f"| {c} | {n} | {g:.0f} | ${g / 1000 * PRICE_PER_KG_ASSUMED:.2f} | {int(spools)} |")
            tg += g
            tc += spools
        lines += [f"| **total** | **{tot}** | **{tg:.0f}** | **${tg / 1000 * PRICE_PER_KG_ASSUMED:.2f}** | **{int(tc)} spools (10 colours)** |", "",
                  "Consumed-filament cost is far below the cost of buying ten whole spools; the spool column is what you must buy.", ""]
        sl = [r for r in SLICE if f"/{v}/" in r["plate"]]
        if sl:
            lines += [f"**Slicer totals ({len(sl)} plates, Bambu Studio {SLICE_META['bambu_studio']}):** "
                      f"{sum(r['time_h'] for r in sl):.1f} h printing, {sum(r['filament_g'] for r in sl):.0f} g filament "
                      "(excludes failed prints and purge). Per plate: `validation/slicer/slicer-checks.md`.", ""]
    cal = [r for r in rows if not r["production"]]
    lines += ["## Calibration coupons (separate from production inventory)", "",
              "| Part | Colour | Qty | Est. g total |", "|---|---|---:|---:|"]
    for r in cal:
        lines.append(f"| `{r['part_id']}` | {r['color']} | {r['qty']} | {r['est_mass_g_total']} |")
    lines += ["", f"Calibration objects: **{sum(r['qty'] for r in cal)}**, about {sum(r['est_mass_g_total'] for r in cal):.0f} g."]
    (pr / "BOM.md").write_text("\n".join(lines) + "\n")

    # packages
    src_files = [HERE / f for f in ("params.json", "build.py", "assemblies.py", "validate.py", "package.py", "reference_sheet.py", "concepts.py", "worstcase_drawing.py", "gallery_content.py", "slice_check.py", "requirements.txt", "render.mjs", "gallery_qa.mjs")] + \
        sorted((HERE / "muju_physical").glob("*.py"))
    dl = OUT / "downloads"
    dl.mkdir(exist_ok=True)
    pkgs = {}
    for v in ("facet", "pebble", "turned"):
        z = dl / f"muju-physical-{v}.zip"
        with zipfile.ZipFile(z, "w", zipfile.ZIP_DEFLATED) as zf:
            for p in MAN["parts"]:
                if p["production"] and p["variant"] in (v, "shared"):
                    zf.write(OUT / p["geometry"]["stl"], f"stl/{Path(p['geometry']['stl']).name}")
            for f in sorted((pr / v / "plates").glob("*.3mf")):
                zf.write(f, f"plates-3mf/{f.name}")
            for f in ("README.md", "BOM.md", "BOM.csv", "PHYSICAL-TEST-SEQUENCE.md"):
                if (pr / f).exists():
                    zf.write(pr / f, f)
            for f in src_files:
                if f.exists():
                    zf.write(f, f"source/{f.relative_to(HERE)}")
        pkgs[v] = z
    z = dl / "muju-physical-calibration-IF1.zip"
    with zipfile.ZipFile(z, "w", zipfile.ZIP_DEFLATED) as zf:
        for p in MAN["parts"]:
            if not p["production"]:
                zf.write(OUT / p["geometry"]["stl"], f"stl/{Path(p['geometry']['stl']).name}")
        for f in sorted((pr / "calibration").glob("*.3mf")):
            zf.write(f, f"plates-3mf/{f.name}")
        for f in ("PHYSICAL-TEST-SEQUENCE.md", "README.md"):
            if (pr / f).exists():
                zf.write(pr / f, f)
    pkgs["calibration"] = z
    z = dl / "muju-physical-source.zip"
    with zipfile.ZipFile(z, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in src_files:
            if f.exists():
                zf.write(f, f"cad/{f.relative_to(HERE)}")
        zf.write(OUT / "manifest.json", "manifest.json")
        zf.write(OUT / "assemblies" / "assemblies.json", "assemblies/assemblies.json")
    pkgs["source"] = z
    # verify archives and write checksums
    sums = []
    for p in sorted(list(OUT.glob("downloads/*.zip")) + list(OUT.glob("print/**/*.3mf")) + list(OUT.glob("models/**/*.stl")) +
                    list(OUT.glob("models/**/*.step")) + list(OUT.glob("models/**/*.glb")) + [pr / "BOM.csv", OUT / "manifest.json"]):
        if p.suffix == ".zip":
            with zipfile.ZipFile(p) as zf:
                assert zf.testzip() is None, p
        sums.append(f"{sha(p)}  {p.relative_to(OUT)}")
    (OUT / "SHA256SUMS").write_text("\n".join(sums) + "\n")
    print({k: f"{v.stat().st_size / 1e6:.1f} MB" for k, v in pkgs.items()}, len(sums), "checksums")


if __name__ == "__main__":
    main()
