/**
 * Lane T (p3 retune, 2026-09-22) sweep orchestrator (SPEC section 3, section 0's
 * heavy-queue rule). Re-runnable: skips any row whose `<outDir>/summary.md`
 * already has `- status: **complete**`. Runs ladder rows TWO AT A TIME
 * (`MUJU_HEAVY_SLOTS=8`, each row `--shards 4`, so two concurrent rows exactly
 * fill the shared heavy queue). Appends one line per FINISHED row to
 * `../PROGRESS.md` (never re-appends a row this process finds already
 * complete on start -- the marker is the outDir path already present in
 * PROGRESS.md).
 *
 * Usage (from `muju/`):
 *   node --import tsx docs/hard-ai/phasing/p3-retune-2026-09-22/scripts/sweep.ts <plan.json> [--concurrency 2]
 *
 * Plan file: a JSON array of rows (see `PlanRow` below). Stage plan files live
 * next to this script (`stageA-plan.json` etc.), generated by
 * `gen-plan-stageA.ts` / hand-written for B/C once earlier stages pick arms.
 */
import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, appendFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

interface PlanRow {
  id: string;
  stage: 'probe' | 'A' | 'B' | 'C';
  arm: string;
  weightsFile: string | null;
  engineA: string;
  engineB: string;
  work: string;
  pairs: number;
  seed: number;
  openings: string;
  shards: number;
  outDir: string; // relative to muju root
  note?: string;
}

const REPO_ROOT = path.resolve(new URL('../../../../../', import.meta.url).pathname); // muju/
const PROGRESS_PATH = path.resolve(new URL('../PROGRESS.md', import.meta.url).pathname);

function isRowComplete(outDir: string): boolean {
  const p = path.join(REPO_ROOT, outDir, 'summary.md');
  if (!existsSync(p)) return false;
  const txt = readFileSync(p, 'utf8');
  return /^- status: \*\*complete\*\*/m.test(txt);
}

function progressHasRow(outDir: string): boolean {
  if (!existsSync(PROGRESS_PATH)) return false;
  const txt = readFileSync(PROGRESS_PATH, 'utf8');
  return txt.includes(`[${outDir}]`);
}

interface GameRow {
  winner: string | null;
  winType: string;
  completedTurns: number;
  upkeepElimination: boolean;
  invariantViolation: unknown;
  adjudicated: boolean;
  anomalies: unknown;
  players: Record<'white' | 'black', {
    bot: string;
    resourcesGained: number;
    resourcesSpent: number;
    promotions: number;
    unitsPlaced: number;
    illegalActions: number;
  }>;
}

function computeBehaviour(gamesPath: string): {
  n: number; spendPct: number; promosPerGame: number; minedA: number; minedB: number;
  upkeepElimPct: number; illegal: number; anyIllegalOrAnomaly: boolean;
} {
  if (!existsSync(gamesPath)) return { n: 0, spendPct: NaN, promosPerGame: NaN, minedA: NaN, minedB: NaN, upkeepElimPct: NaN, illegal: 0, anyIllegalOrAnomaly: false };
  const lines = readFileSync(gamesPath, 'utf8').trim().split('\n').filter(Boolean);
  const games: GameRow[] = lines.map(l => JSON.parse(l));
  let spent = 0, gained = 0, prom = 0, minedA = 0, minedB = 0, upkeepElim = 0, illegal = 0, anomaly = 0;
  for (const g of games) {
    const aSeat: 'white' | 'black' = g.players.white.bot.startsWith('hard@') ? 'white' : 'black';
    const bSeat: 'white' | 'black' = aSeat === 'white' ? 'black' : 'white';
    const pa = g.players[aSeat];
    const pb = g.players[bSeat];
    spent += pa.resourcesSpent;
    gained += pa.resourcesGained;
    prom += pa.promotions;
    minedA += pa.resourcesGained;
    minedB += pb.resourcesGained;
    if (g.upkeepElimination) upkeepElim++;
    illegal += pa.illegalActions + pb.illegalActions;
    if (g.invariantViolation) anomaly++;
  }
  const n = games.length;
  return {
    n,
    spendPct: n ? (100 * spent / gained) : NaN,
    promosPerGame: n ? prom / n : NaN,
    minedA: n ? minedA / n : NaN,
    minedB: n ? minedB / n : NaN,
    upkeepElimPct: n ? (100 * upkeepElim / n) : NaN,
    illegal,
    anyIllegalOrAnomaly: illegal > 0 || anomaly > 0,
  };
}

interface Metrics {
  wins: number; draws: number; losses: number;
  strata: { score: number }[];
  voided: boolean; voidReason: string | null;
  loadAvgMean: number;
}

function readMetrics(outDir: string): Metrics | null {
  const p = path.join(REPO_ROOT, outDir, 'metrics.json');
  if (!existsSync(p)) return null;
  return JSON.parse(readFileSync(p, 'utf8'));
}

function appendProgress(line: string): void {
  appendFileSync(PROGRESS_PATH, line.endsWith('\n') ? line : line + '\n');
}

function logRow(row: PlanRow): void {
  const metrics = readMetrics(row.outDir);
  if (!metrics) {
    appendProgress(`- ${row.arm} | ${row.engineB} | ${row.stage} | NO METRICS.JSON | [${row.outDir}]`);
    return;
  }
  const behaviour = computeBehaviour(path.join(REPO_ROOT, row.outDir, 'games.jsonl'));
  const score = metrics.strata.length ? metrics.strata.reduce((s, x) => s + x.score, 0) / metrics.strata.length : NaN;
  const voidStr = metrics.voided ? `VOID (${metrics.voidReason})` : 'valid';
  const line =
    `- ${row.arm} | ${row.engineB} | ${row.stage} | ${metrics.wins}-${metrics.draws}-${metrics.losses} | ` +
    `score ${score.toFixed(3)} | spend ${behaviour.spendPct.toFixed(0)}% | promo/g ${behaviour.promosPerGame.toFixed(2)} | ` +
    `mined ${behaviour.minedA.toFixed(0)}/${behaviour.minedB.toFixed(0)} | upkeepElim ${behaviour.upkeepElimPct.toFixed(0)}% | ` +
    `illegal ${behaviour.illegal} | ${voidStr} | load ${metrics.loadAvgMean.toFixed(1)} | [${row.outDir}]`;
  appendProgress(line);
}

async function runRow(row: PlanRow): Promise<void> {
  const outAbs = path.join(REPO_ROOT, row.outDir);
  mkdirSync(outAbs, { recursive: true });
  const args = [
    '--import', 'tsx', 'lab/hard-ai/ladder/run.ts',
    '--a', row.engineA, '--b', row.engineB,
    '--work', row.work, '--handicaps', '0',
    '--pairs', String(row.pairs), '--seed', String(row.seed),
    '--openings', row.openings, '--replays', 'off',
    '--shards', String(row.shards), '--out', row.outDir,
  ];
  const env = { ...process.env, MUJU_HEAVY_SLOTS: process.env.MUJU_HEAVY_SLOTS ?? '8' };
  delete env.MUJU_HEAVY_BYPASS;
  if (row.weightsFile) env.MUJU_HARD_WEIGHTS = path.resolve(REPO_ROOT, row.weightsFile);
  else delete env.MUJU_HARD_WEIGHTS;

  const logPath = path.join(outAbs, 'sweep-run.log');
  await new Promise<void>((resolve, reject) => {
    const child = spawn('node', args, { cwd: REPO_ROOT, env });
    const chunks: Buffer[] = [];
    child.stdout.on('data', d => chunks.push(d));
    child.stderr.on('data', d => chunks.push(d));
    child.on('close', code => {
      writeFileSync(logPath, Buffer.concat(chunks));
      if (code === 0) resolve();
      else reject(new Error(`row ${row.id} exited ${code}; see ${logPath}`));
    });
    child.on('error', reject);
  });
}

async function main(): Promise<void> {
  const planPath = process.argv[2];
  if (!planPath) throw new Error('usage: sweep.ts <plan.json> [--concurrency N]');
  const concIdx = process.argv.indexOf('--concurrency');
  const concurrency = concIdx >= 0 ? Number(process.argv[concIdx + 1]) : 2;
  const plan: PlanRow[] = JSON.parse(readFileSync(planPath, 'utf8'));

  const pending = plan.filter(row => {
    if (isRowComplete(row.outDir)) {
      if (!progressHasRow(row.outDir)) logRow(row); // was completed by an earlier invocation; log it now
      console.log(`skip (already complete): ${row.id}`);
      return false;
    }
    return true;
  });
  console.log(`${pending.length} of ${plan.length} rows to run, concurrency ${concurrency}`);

  for (let i = 0; i < pending.length; i += concurrency) {
    const batch = pending.slice(i, i + concurrency);
    console.log(`batch ${i / concurrency + 1}: ${batch.map(r => r.id).join(', ')}`);
    const results = await Promise.allSettled(batch.map(runRow));
    for (let j = 0; j < batch.length; j++) {
      const row = batch[j];
      const res = results[j];
      if (res.status === 'rejected') {
        console.error(`FAILED: ${row.id}: ${res.reason}`);
        appendProgress(`- ${row.arm} | ${row.engineB} | ${row.stage} | FAILED: ${res.reason} | [${row.outDir}]`);
        continue;
      }
      logRow(row);
      console.log(`done: ${row.id}`);
    }
  }
  console.log('sweep: all rows in this plan attempted');
}

main().catch(err => {
  console.error(err);
  process.exitCode = 1;
});
