import React from 'react';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
import { renderToStaticMarkup } from 'react-dom/server';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { UnitArtwork } from '../src/components/UnitArtwork';
import { CrystalWell } from '../src/components/CrystalWell';
const elements = ['fire','lightning','water','shadow','plant','metal'] as const;
const tiers = [1,2,3,4] as const;
const examples=[{n:5,d:0,name:'Untouched',caption:'5 crystals · next depth 1'},{n:3,d:0,name:'Thin seam',caption:'3 crystals · next depth 1'},{n:3,d:2,name:'Excavated',caption:'3 crystals · next depth 3'},{n:1,d:4,name:'Deep remnant',caption:'1 crystal · next depth 5'},{n:1,d:0,name:'Shallow remnant',caption:'1 crystal · next depth 1'},{n:0,d:5,name:'Empty',caption:'No crystals left'}];
const css=readFileSync(root + '/dist/assets/'+readdirSync(root + '/dist/assets').find(x=>x.endsWith('.css')),'utf8');
const view=<main className="reference-sheet"><header><span className="eyebrow">MUJU HONO TANKA / VISUAL SYSTEM</span><h1>Crystal wells. Elemental armies.</h1><p>Reserve brightness · excavated depth · distinct army shapes · one symbol per element</p></header>
<section className="reference-wells">{examples.map(({n,d,name,caption})=><figure key={name}><div className={`board-cell depth-${n}`}><CrystalWell cell={{position:{x:0,y:0},resourceLayers:n,minedDepth:d}} /></div><figcaption><b>{name}</b><small>{caption}</small></figcaption></figure>)}</section>
<p className="reading">Read the gauge from top to bottom: <b>lit = crystal</b> · hollow = mined · dash = bedrock. <br/>The first lit slot tells you the Mining needed. Equal reserves can sit at different depths.</p>
<div className="reference-armies">{(['white','black'] as const).map(owner=><section key={owner}><h2>{owner==='white'?'Ivory army':'Obsidian army'}</h2><p>{owner==='white'?'Round pale stone · dark symbols':'Angular dark stone · luminous symbols'}</p><div className="catalogue-head">{elements.map(e=><span key={e}>{e}</span>)}</div>{tiers.map(tier=><div className="catalogue-row" key={tier}>{elements.map(element=><figure key={element}><UnitArtwork owner={owner} element={element} tier={tier}/></figure>)}</div>)}<footer>Tier 1 → 4, top to bottom · count the base marks</footer></section>)}</div><aside><strong>Still readable without color.</strong> Base shape identifies the army; silhouettes identify the element. Higher ranks gain a larger base, extra rim, and a tier-four crest. Tap a piece for actual attack, defense, speed, and mining.</aside></main>;
writeFileSync(process.argv[2] ?? '/private/tmp/muju-visual-reference.html','<!DOCTYPE html><meta charset="utf-8"><style>'+css+`body {padding:36px;background:#101925;color:#e5edf1}.reference-sheet{width:1000px;margin:auto;font:14px/1.5 system-ui}.eyebrow{font-size:11px;letter-spacing:2px;color:#a8d7ca}h1{font-size:36px;font-weight:750;letter-spacing:-1.3px;margin:8px 0}header p{color:#a8bfca}.reference-wells{display:grid;grid-template-columns:repeat(6,1fr);gap:20px;margin:28px 0 12px}.reference-wells .board-cell{position:relative;width:100%;height:114px;border-radius:6px;overflow:hidden}.reference-wells figcaption{margin-top:10px;font-size:12px}.reference-wells small{display:block;color:#9fb7c6;font-size:10px}.reading{font-size:12px;color:#abc2ce;line-height:1.7;margin:16px 0 24px}.reference-armies{display:grid;grid-template-columns:1fr 1fr;gap:24px}.reference-armies section{border:1px solid #314757;border-radius:16px;padding:20px;background:#172838}.reference-armies h2{font-size:21px;font-weight:750}.reference-armies p{font-size:11px;color:#a8becc;margin:0 0 16px}.catalogue-head,.catalogue-row{display:grid;grid-template-columns:repeat(6,1fr);gap:7px;text-align:center}.catalogue-head{font-size:10px;text-transform:capitalize;color:#aec2cf}.catalogue-row{margin-top:10px}.catalogue-row figure{padding:5px 4px;background:#0c1b2633;border-radius:10px}.catalogue-row .unit-art{width:45px;height:49px;margin:auto}.reference-armies footer{font-size:10px;color:#a4bdc8;margin-top:14px}aside{margin-top:22px;color:#a8becb;font-size:12px;max-width:880px}aside strong{color:#d9eadf}`+'</style>'+renderToStaticMarkup(view));
