import type { Arc } from '../types';

export const ARC: Arc = {
  id: 'elements', title: 'Elements', part: 'combat', icon: 'elements',
  puzzles: [
    {
      id: 'elements-1',
      idea: 'Fire burns Plant: the Hi\'s 2 + 1 = 3 removes a Muju (DEF 3), the first +1 in the preview.',
      board: [
        'F1 .  .',
        '.  p1 .',
        '.  .  .',
      ],
      goal: { kind: 'capture', targets: ['b2'] },
      solution: ['a1-a2xb2'],
    },
    {
      id: 'elements-2',
      idea: 'Water douses Fire: the Hi does only 2 − 1 = 1 to a Sjór, but the humble Poṉ (Metal beats Water) does 1 + 1 = 2.',
      board: [
        'F1 .  .  .',
        '.  .  .  .',
        '.  .  .  .',
        '.  .  M1 w1',
      ],
      goal: { kind: 'capture', targets: ['d4'] },
      solution: ['c4xd4'],
      tries: [['a1-d3xd4']],
    },
    {
      id: 'elements-3',
      idea: 'Lightning is Fire\'s partner: the Poṉ does 1 − 1 = 0 to a Radi, and the Sjór (Water beats Lightning) walks over to take it.',
      board: [
        '.  .  M1 l1',
        '.  .  .  .',
        '.  W1 .  .',
        '.  .  .  .',
      ],
      goal: { kind: 'capture', targets: ['d1'] },
      solution: ['b3-d2xd1'],
      tries: [['c1xd1']],
    },
    {
      id: 'elements-4',
      idea: 'Plant and Metal beat Water and Shadow: the Poṉ takes the Sjór again, and the slow Mallki (1 + 1 = 2) walks over to take the Loş. The Hi beside the Loş does only 2 − 1 = 1.',
      board: [
        'M1 w1 .  .',
        '.  .  .  .',
        '.  P2 .  F1',
        '.  .  .  s1',
      ],
      goal: { kind: 'capture', targets: ['b1', 'd4'] },
      solution: ['a1xb1', 'b3-c4xd4'],
      tries: [['d3xd4'], ['b3-b2xb1']],
    },
    {
      id: 'elements-5',
      idea: 'The other side of Plant beats Shadow: a Gölge does 3 − 1 = 2 to a Muju (DEF 3), so the far Hi (2 + 1 = 3) must come.',
      board: [
        '.  .  .  F1',
        '.  .  .  .',
        'S2 .  .  .',
        'p1 .  .  .',
      ],
      goal: { kind: 'capture', targets: ['a4'] },
      solution: ['d1-b4xa4'],
      tries: [['a3xa4']],
    },
    {
      id: 'elements-6',
      idea: 'Same pair is neutral: the Radi\'s plain 1 takes the Hi and the Sjór\'s plain 2 takes the Loş. Sending the Sjór at the Hi (+1) leaves the Radi doing 0 to the Loş.',
      board: [
        'L1 .  .  .',
        '.  W1 .  f1',
        '.  .  .  .',
        '.  s1 .  .',
      ],
      goal: { kind: 'capture', targets: ['b4', 'd2'] },
      solution: ['a1-c2xd2', 'b2-b3xb4'],
      tries: [['b2-c2xd2'], ['a1-b3xb4'], ['b2-c2xd2', 'a1-b3xb4']],
    },
    {
      id: 'elements-7',
      idea: 'Defense never changes: the element is in the attack, not the shield. Water only takes 1 off Fire\'s attack, so a Honō (3 − 1 = 2) still removes the Sjór (DEF 2); the Muju beside it has the edge but only 0 + 1 = 1.',
      board: [
        'F2 .  .  .',
        '.  .  .  .',
        '.  .  .  .',
        '.  .  P1 w1',
      ],
      goal: { kind: 'capture', targets: ['d4'] },
      solution: ['a1-d3xd4'],
      tries: [['c4xd4']],
    },
    {
      id: 'elements-8',
      idea: 'Assignment: each attacker takes the one it beats. Hi on Muju, Poṉ on Loş, Sjór on Radi; the Hi on the Loş and the Poṉ on the Radi look like kills and are not.',
      board: [
        '.  .  p1',
        'W1 .  F1',
        'l1 M1 s1',
      ],
      goal: { kind: 'eliminate' },
      solution: ['c2xc1', 'b3xc3', 'a2xa3'],
      tries: [['c2xc3'], ['b3xa3']],
    },
    {
      id: 'elements-9',
      idea: 'Assignment with travel: the Mallki and the Hi stand beside the wrong targets too, and the fast Radi can only hurt the Hi, so it must run to it.',
      board: [
        '.  .  L1 .  .',
        '.  .  .  .  .',
        'f1 P2 w1 F1 m1',
        '.  .  .  .  .',
        '.  .  .  .  .',
      ],
      goal: { kind: 'eliminate' },
      solution: ['d3xe3', 'b3xc3', 'c1-a2xa3'],
      tries: [['d3xc3'], ['b3xa3'], ['c1-c2xc3']],
    },
    {
      id: 'elements-10',
      idea: 'Conclusion with mining: the Mallki needs the 5 under the Sjór. The Hi burns the Muju out of the doorway (3 vs 3) and the Poṉ removes the Sjór (1 + 1 = 2); the Mallki walks the cleared corridor onto the 5. The Hi can do nothing to the Sjór and the Mallki nothing to the Muju; the near 3 is one short. (The Mallki may also kill the Sjór itself and step on.)',
      board: [
        '.  .  .     .  .',
        '.  F1 .     .  .',
        'P2 p1 w1+5  .  .',
        '3  .  M1    .  .',
        '.  .  .     .  m1',
      ],
      goal: { kind: 'mine', atLeast: 5 },
      solution: ['b2xb3', 'c4xc3', 'a3-c3', 'mine'],
      tries: [['a3-a4', 'mine'], ['b2-c2xc3'], ['a3xb3'], ['b2xb3', 'c4xc3', 'b2-c3', 'a3-a4', 'mine']],
    },
  ],
};
