import type { Arc } from '../types';

export const ARC: Arc = {
  id: 'move', title: 'Moving', part: 'basics', icon: 'move',
  puzzles: [
    {
      id: 'move-1', idea: 'Tap a piece, tap a square: one step costs one action.',
      board: [
        '.  P1 .',
        '.  .  .',
        '.  .  .',
      ],
      goal: { kind: 'reach', flags: ['b2'] },
      solution: ['b1-b2'],
    },
    {
      id: 'move-2', idea: 'A walk of four squares spends all four actions, one per square for a Muju; the action pips count down to zero.',
      board: [
        '.  .  P1 .  .',
        '.  .  .  .  .',
        '.  .  .  .  .',
        '.  .  .  .  .',
        '.  .  .  .  .',
      ],
      goal: { kind: 'reach', flags: ['c5'] },
      solution: ['c1-c5'],
      tries: [['c1-c2', 'mine'], ['c1-b1']],
    },
    {
      id: 'move-3', idea: 'Moves are orthogonal only: the Muju that looks closer on the diagonal is five steps from the flag; the one straight along the row is exactly four.',
      board: [
        '.  .  P1 .  .',
        '.  .  .  .  .',
        '.  .  .  .  .',
        'P1 .  .  .  .',
        '.  .  .  .  .',
      ],
      goal: { kind: 'reach', flags: ['e4'] },
      solution: ['a4-e4'],
      tries: [['c1-c2'], ['c1-e3']],
    },
    {
      id: 'move-4', idea: 'Speed is squares per action: the near Muju (Speed 1) needs five actions; the far Hi (Speed 2) covers eight squares in four.',
      board: [
        '.  .  .  .  .  .',
        'F1 .  .  .  .  .',
        '.  .  P1 .  .  .',
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
      ],
      goal: { kind: 'reach', flags: ['e6'] },
      solution: ['a2-e6'],
      tries: [['c3-c4'], ['a2-a3']],
    },
    {
      id: 'move-5', idea: 'One trip rounds up once: eight squares in a single trip cost four actions, but an L along the edges (three squares, then five) rounds up twice and costs five, and so does stepping one square first.',
      board: [
        '.  .  .  F1 .  .',
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
      ],
      goal: { kind: 'reach', flags: ['a6'] },
      solution: ['d1-a6'],
      tries: [['d1-a1'], ['d1-d6'], ['d1-d2']],
    },
    {
      id: 'move-6', idea: 'Four actions for the team: the Hi beside the near flag must take the far one (two actions) so the Muju can walk to the near one (two actions); grabbing the near flag with the Hi strands the Muju.',
      board: [
        '.  .  .  .  .',
        '.  .  F1 .  .',
        'P1 .  .  .  .',
        '.  .  .  .  .',
        '.  .  .  .  .',
      ],
      goal: { kind: 'reach', flags: ['c3', 'e4'] },
      solution: ['a3-c3', 'c2-e4'],
      tries: [['c2-c3']],
    },
    {
      id: 'move-7', idea: 'Pieces block, friends too: the Hi is boxed into the corner by its own Mujus; the one in the row must step down out of it (one action), then the Hi runs five squares (three). Stepping along the row leaves a seven-square detour.',
      board: [
        '.  .  .  .  P1 F1',
        '.  .  .  .  .  P1',
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
      ],
      goal: { kind: 'reach', flags: ['a1'], piece: 'f1' },
      solution: ['e1-e2', 'f1-a1'],
      tries: [['e1-d1'], ['f2-f3'], ['e1-a1']],
    },
    {
      id: 'move-8', idea: 'Speed 0: the Poṉ beside the flag cannot move, and the Muju is a step too slow; the far Radi (Speed 3) crosses ten squares in four actions.',
      board: [
        '.  .  .  .  .  .',
        '.  .  .  .  .  M1',
        '.  .  .  .  .  .',
        '.  .  .  P1 .  .',
        '.  .  .  .  .  .',
        'L1 .  .  .  .  .',
      ],
      goal: { kind: 'reach', flags: ['f1'] },
      solution: ['a6-f1'],
      tries: [['d4-d3'], ['a6-a5', 'a5-a4']],
    },
    {
      id: 'move-9', idea: 'A first look at winning: walk the Hi into the enemy home, then Mine & prepare. The Sjór is too far to reach it, so it is home checkmate. Your own Poṉ blocks the right edge and the Sjór the left, so the Hi cuts through the middle in one eight-square trip; an edge route costs five. Hitting the Sjór only wastes actions.',
      board: [
        'F1 .  .  .  .',
        '.  .  .  .  .',
        '.  .  .  .  .',
        'w1 .  .  .  M1',
        '.  .  .  .  .',
      ],
      homes: true,
      goal: { kind: 'home' },
      solution: ['a1-e5', 'mine'],
      tries: [['a1-e1'], ['a1-a5'], ['a1-a3xa4']],
    },
  ],
};
