import type { Arc } from '../types';

/**
 * Mixed review: no arc label, every rule, bigger boards (5×5 to 7×7). Each
 * position mixes two or three earlier arcs and runs the player's checklist:
 * can I win now (home or elimination), can I capture, am I safe, can I earn
 * more? Puzzles 1–3 introduce the mix (a sweep, a hit and run, earning in
 * reach of a slow enemy), 4–7 develop it with the economy (two of them over
 * two turns), 8–12 are twists where the checklist surprises (your own rent is
 * a danger, a summon is not a guard, a real piece blocks their summon, winning
 * now beats running, their invader on your home cancels your checkmate), and
 * 13–14 conclude by checking every danger at once and by clearing and holding
 * the enemy home. Nothing here shares a mechanism with the Final exam: the
 * chip-then-chain capture and the walk-in-and-promote mate live there.
 */
export const ARC: Arc = {
  id: 'review', title: 'Mixed review', part: 'review', icon: 'review',
  puzzles: [
    {
      id: 'review-1',
      idea: 'Sweep: Fire takes Plant and Metal in one chain, Metal takes Water. The Hi\'s blow on the Sjór would only chip it and close its chain.',
      board: [
        '.  .  .  .  .  .',
        '.  .  w1 M1 .  .',
        '.  p1 F1 .  .  .',
        '.  .  .  .  .  .',
        '.  .  .  m1 .  .',
        '.  .  .  .  .  .',
      ],
      goal: { kind: 'eliminate' },
      solution: ['c3xb3', 'c3-c5xd5', 'd2xc2'],
      tries: [['c3xc2', 'd2xc2']],
    },
    {
      id: 'review-2',
      idea: 'Hit and run between two kinds of danger: the Poṉ cannot move, so one step away from it is enough, but the Straumr walks three and hits, so count to five. The Sjór (2 + 1 = 3) takes the Hi from the square beside the Poṉ, and the Hi\'s own square is the only one clear of both.',
      board: [
        '.  .  .  .  .',
        '.  .  m1 W1 .',
        '.  f1 .  .  .',
        '.  .  .  .  .',
        '.  .  .  .  w2+2',
      ],
      goal: { kind: 'all', goals: [{ kind: 'capture', targets: ['b3'] }, { kind: 'survive' }] },
      solution: ['d2-c3xb3', 'c3-b3', 'mine', 'end'],
      tries: [['d2-c3xb3', 'mine', 'end'], ['d2-c3xb3', 'c3-c4', 'mine', 'end'], ['d2-c3xb3', 'c3-d3', 'mine', 'end']],
    },
    {
      id: 'review-3',
      idea: 'Earn and stay safe: the Sjór sits on the rich square inside the Straumr\'s reach. Water does only 1 to Plant, so the Muju takes the 6, and the Sjór walks to the 2, five squares from the Straumr and out of its trip plus hit: 3 + 2.',
      board: [
        '.  .  .  2  .  .',
        '.  .  P1 .  .  .',
        '.  .  .  W1+6 .  .',
        '.  .  .  .  .  .',
        '.  .  .  .  w2 .',
        '.  .  .  .  .  .',
      ],
      banks: { black: 1 },
      goal: { kind: 'all', goals: [{ kind: 'mine', atLeast: 5 }, { kind: 'survive' }] },
      solution: ['d3-d1', 'c2-d3', 'mine', 'end'],
      tries: [['c2-d1', 'mine', 'end'], ['d3-d1', 'mine', 'end']],
    },
    {
      id: 'review-4',
      idea: 'Rent comes out before Prepare: the Mallki on the 4 nets 4 − 1 = 3, a crystal short of a Sjór, so it walks to the 6 (5 − 1 = 4). Neither rectangle covers the flag, so the Hi steps past it to anchor one that does.',
      board: [
        '.  .  .  .  F1 .',
        '.  .  .  .  .  .',
        '.  P2+4 .  .  .  .',
        '.  .  .  .  .  .',
        '.  6  .  .  .  .',
        '.  .  .  .  m1 .',
      ],
      homes: true,
      goal: { kind: 'summon', type: 'W1', at: ['e2'] },
      solution: ['b3-b5', 'e1-f2', 'mine', '+W1@e2', 'end'],
      tries: [['e1-f2', 'mine'], ['b3-b5', 'mine']],
    },
    {
      id: 'review-5',
      idea: 'Count both defenders: the Gölge (3 − 1) and the Sjór (2 − 1) add up to 3, enough to remove a Muju (DEF 3) but not a Veḷḷi (DEF 4). The Veḷḷi needs every action, and the home\'s 2 crystals pay its rent.',
      board: [
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
        '.  .  .  F1 .  .',
        '.  .  .  .  P1 w1',
        '.  .  M2 .  .  .',
        '.  .  .  s2 .  2',
      ],
      homes: true,
      goal: { kind: 'home' },
      solution: ['c5-f6', 'mine'],
      tries: [['e4-f6', 'mine', 'end'], ['d3-f6', 'mine', 'end']],
    },
    {
      id: 'review-6',
      idea: 'Buy a miner: the bank of 2 plus this turn\'s 3 buys a Muju (5), which lands next turn, walks onto the 3 and mines: 3 + 3 + 3 = 9. Promoting to a Mallki gives only 3 + 5, a Sjór 3 + 3 + 2, and a Poṉ cannot walk to the crystals.',
      board: [
        '.  .  .  .  .',
        '.  P1+16 .  .  .',
        '3  .  .  .  .',
        '.  .  .  .  m1',
        '.  .  .  .  .',
      ],
      homes: true,
      turns: 2,
      banks: { white: 2 },
      goal: { kind: 'mine', atLeast: 9 },
      solution: ['mine', '+P1@a2', 'end'],
      tries: [['mine', '^b2', 'end'], ['mine', '+W1@a2', 'end'], ['mine', 'end']],
    },
    {
      id: 'review-7',
      idea: 'Choose what to keep: one crystal pays one rent. Fire beats Metal (3 + 1 = 4) while Shadow loses to it (3 − 1 = 2), so keep the far Honō, not the Gölge beside the Poṉ.',
      board: [
        'F2 .  .  .  .',
        '.  .  .  .  .',
        '.  .  .  .  .',
        '.  .  .  S2 .',
        '.  .  .  .  m1',
      ],
      turns: 2,
      banks: { white: 1 },
      goal: { kind: 'capture', targets: ['e5'] },
      solution: ['a1-d5', 'mine', 'keep d5', 'end'],
      tries: [['a1-d5', 'mine', 'keep d4', 'end']],
    },
    {
      id: 'review-8',
      idea: 'Am I safe includes my own rent: the Honō escapes the Straumr in two actions, but with an empty bank it is lost at upkeep unless the Muju walks onto crystals to pay its 1.',
      board: [
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
        '.  .  F2 .  .  .',
        '.  .  .  w2 .  .',
        '.  .  .  .  .  .',
        '.  P1 .  2  .  .',
      ],
      banks: { black: 1 },
      goal: { kind: 'survive' },
      solution: ['c3-a1', 'b6-d6', 'mine', 'end'],
      tries: [['c3-a1', 'mine'], ['b6-d6', 'mine', 'end']],
    },
    {
      id: 'review-9',
      idea: 'A pending summon is not a guard: it lands only after their turn, and their Hi on your home would block every rectangle anyway. The Sjór is the only piece of yours that can hurt the Hi, so it leaves its crystals and spends all four actions walking back within reach of your home (three steps and a hit next turn). Their Muju sits on their home, so there is no checkmate shortcut.',
      board: [
        '.  .  .  .  .  f1',
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
        '.  .  .  .  W1+4 .',
        '.  .  .  .  .  p1',
      ],
      homes: true,
      banks: { white: 3 },
      goal: { kind: 'hold' },
      solution: ['e5-c3', 'mine', 'end'],
      tries: [['mine', '+F1@a2', 'end'], ['mine', '+W1@b1', 'end']],
    },
    {
      id: 'review-10',
      idea: 'Block the arrival: the pending Hi lands next turn and strikes at once, and the slow Muju cannot outrun it. A summon needs an empty square inside a clear rectangle, so the Muju walks into the Poṉ\'s rectangle and the Hi is refunded.',
      board: [
        '.  .  .  .  .',
        '.  .  P1 .  .',
        '.  .  .  .  .',
        '.  m1 .  .  .',
        '.  .  .  .  .',
      ],
      homes: true,
      pending: [{ at: 'c4', type: 'F1', owner: 'black' }],
      goal: { kind: 'survive' },
      solution: ['c2-c4', 'mine', 'end'],
      tries: [['c2-a1', 'mine', 'end'], ['mine', 'end']],
    },
    {
      id: 'review-11',
      idea: 'Can I win now comes first: the Loş reaches the Sjór anywhere (Speed 2: six squares and a hit) and nothing of yours can touch it, so running only picks the square the Sjór dies on. The Muju walks into the enemy home instead: Shadow does 2 − 1 = 1 to Plant, so the Loş cannot remove it, and the checkmate ends the game before the reply. The Poṉ on your home keeps the Loş from winning the same way.',
      board: [
        'M1 .  .  .  .  .',
        '.  .  .  s1 .  P1',
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
        '.  W1 .  .  .  .',
        '.  .  .  .  .  .',
      ],
      homes: true,
      goal: { kind: 'survive' },
      solution: ['f2-f6', 'mine'],
      tries: [['b5-a6', 'mine', 'end'], ['b5-b2', 'mine', 'end'], ['f2-f5', 'mine', 'end'], ['f2-f4', 'b5-b4', 'mine', 'end']],
    },
    {
      id: 'review-12',
      idea: 'No checkmate while they sit on your home: walking into theirs is not enough. The Poṉ (1 + 1) and the Hi (2 − 1) remove the Straumr from your home, then the Muju steps in.',
      board: [
        'w2 .  F1 .  .  .',
        'M1 .  .  .  .  .',
        '.  .  .  .  .  .',
        '.  .  .  .  .  .',
        '.  .  .  .  s1 P1',
        '.  .  .  .  .  .',
      ],
      homes: true,
      goal: { kind: 'home' },
      solution: ['a2xa1', 'c1-b1xa1', 'f5-f6', 'mine'],
      tries: [['f5-f6', 'mine', 'end'], ['a2xa1', 'c1-b1xa1', 'mine', 'end']],
    },
    {
      id: 'review-13',
      idea: 'Conclusion, am I safe from everything: the Loş would reach the Honō anywhere, so the Honō removes it (3 − 1 = 2); the pending Hi would land and burn the Muju, so the Muju walks into the Poṉ\'s rectangle; and the empty bank owes the Honō\'s rent, so the square it walks onto must hold crystals. Their Poṉ sits on their home, so there is no checkmate shortcut.',
      board: [
        '.  .  .  .  .  .',
        '.  s1 .  .  .  .',
        '.  .  .  .  .  .',
        'F2 .  .  .  m1 .',
        '.  .  .  .  .  .',
        '.  3  P1 .  3  m1',
      ],
      homes: true,
      pending: [{ at: 'e5', type: 'F1', owner: 'black' }],
      goal: { kind: 'survive' },
      solution: ['a4-a2xb2', 'c6-e6', 'mine', 'end'],
      tries: [['a4-a2xb2', 'c6-b6', 'mine', 'end'], ['a4-a2xb2', 'mine'], ['c6-e6', 'a4-a1', 'mine', 'end']],
    },
    {
      id: 'review-14',
      idea: 'Conclusion, clear with one piece and hold with another: the Sjór would remove a Hi or a Kagari on the home, but does only 1 to an Irumbu. The Hi breaks the Muju off the home (2 + 1), the Irumbu walks in, and its 5 crystals mined there pay both tier-3 rents. The Kagari could clear the home and step in, but the Sjór removes it (2 + 1 = 3 against DEF 2), and it mines only 1 against 2 + 2 of rent.',
      board: [
        '.  .  .  .  .  .  .',
        '.  .  .  .  .  .  .',
        '.  .  .  .  .  .  .',
        '.  .  F3 .  .  .  .',
        '.  .  .  .  .  F1 .',
        '.  .  .  .  w1 .  .',
        '.  .  .  M3 .  .  p1+6',
      ],
      homes: true,
      goal: { kind: 'home' },
      solution: ['f5-g6xg7', 'd7-g7', 'mine'],
      tries: [['c4-g6xg7', 'g6-g7', 'mine'], ['f5-g6xg7', 'g6-g7', 'mine']],
    },
  ],
};
