/** P1 allocation: 48 dev, 32 val, 32 sealed + 32 unused spare.
 * Standard split constants/utilities below are retained for archive checks.
 * No historical bytes are regenerated by this entry point. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { mulberry32 } from '../../../harness/rng';
import { sha256, type OpeningSpec } from '../openings';
import { generateOpenings, renderOpeningSpecs, DRIVER_BOTS } from './generate';
import { validateOpenings, RULES_VERSION } from './phasing';

/** Root seed of the E1 pool and of the shuffle that splits it. Distinct from E0's 2026. */
export const E1_SEED = 2027;
/** Namespaces E1 ids away from E0's `g<plies>-s<attempt>` (see `generate.ts`'s module doc). */
export const E1_ID_PREFIX = 'e1-';
/** Pool size asked for: 48 + 32 + 32. */
export const E1_TARGET_COUNT = 112;
/** Attempt budget. The pool is reached in ~1,000 candidates; this is the guard, not the cost. */
export const E1_MAX_ATTEMPTS = 20_000;
/** Pool the E1 set must stay disjoint from, by h0 digest and by prefix relation. */
export const E1_EXCLUDE = 'e0-openings.jsonl';

/** Development : validation : sealed. 112 cuts exactly 48/32/32. */
export const SPLIT_WEIGHTS = { dev: 3, val: 2, sealed: 2 } as const;

/**
 * E0 rows the pilot already ran (E0-PILOT-REPORT §"Pilot 2": `g2-s0` and
 * `g3-s1`, pair ids `g2-s0:0:0`, `g3-s1:0:1`, `g2-s0:3:0`, `g3-s1:3:1`).
 * Held out of the preregistered baseline by A15's "excluding the pilot pairs".
 */
export const E0_PILOT_INDICES = [0, 1] as const;
/** E0 rows reserved for E1.1's eight diagnostic pairs, also excluded from the baseline. */
export const E0_E1_1_INDICES = [2, 3, 4, 5, 6, 7, 8, 9] as const;
/** E0 rows the baseline opens with: everything the pilot and E1.1 do not claim. */
export const E0_BASELINE_INDICES = [10, 11, 12, 13, 14, 15] as const;
/** Pairs per handicap in the preregistered baseline, hence rows in `e1-baseline.jsonl`. */
export const BASELINE_SIZE = 50;

export const FILE_NAMES = {
  dev: 'e1-dev.jsonl',
  val: 'e1-val.jsonl',
  sealed: 'e1-sealed.jsonl',
  baseline: 'e1-baseline.jsonl',
} as const;

/**
 * Fisher-Yates over a copy, drawing from `mulberry32(seed)` — the harness RNG
 * (`lab/harness/rng.ts`), so the shuffle is the same generator every other
 * seeded draw in the lab uses. Descending `i` with `j = floor(rng() * (i+1))`
 * is the unbiased form; the input is never mutated.
 */
export function seededShuffle<T>(items: readonly T[], seed: number): T[] {
  const out = items.slice();
  const rng = mulberry32(seed);
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    const tmp = out[i];
    out[i] = out[j];
    out[j] = tmp;
  }
  return out;
}

export interface Strata {
  dev: OpeningSpec[];
  val: OpeningSpec[];
  sealed: OpeningSpec[];
}

/**
 * Cuts an already-shuffled pool 3:2:2. Validation and sealed are floored, so
 * any remainder lands in development — the stratum that may be inspected, the
 * one it is safe to make bigger.
 */
export function splitShuffled(shuffled: readonly OpeningSpec[]): Strata {
  const total = SPLIT_WEIGHTS.dev + SPLIT_WEIGHTS.val + SPLIT_WEIGHTS.sealed;
  const val = Math.floor((shuffled.length * SPLIT_WEIGHTS.val) / total);
  const sealed = Math.floor((shuffled.length * SPLIT_WEIGHTS.sealed) / total);
  const dev = shuffled.length - val - sealed;
  return {
    dev: shuffled.slice(0, dev),
    val: shuffled.slice(dev, dev + val),
    sealed: shuffled.slice(dev + val),
  };
}

/**
 * The preregistered baseline set, in run order: the six unclaimed E0 rows,
 * then development rows until 50. Fewer than 50 only if the pool came out
 * short — the caller reports the shortfall; validation and sealed are never
 * borrowed from.
 */
export function buildBaseline(e0: readonly OpeningSpec[], dev: readonly OpeningSpec[]): OpeningSpec[] {
  const head = E0_BASELINE_INDICES.map(i => {
    const row = e0[i];
    if (!row) throw new Error(`split: ${E1_EXCLUDE} has no row at index ${i}; the baseline ledger assumes 16 rows`);
    return row;
  });
  return [...head, ...dev.slice(0, BASELINE_SIZE - head.length)];
}


export const P1_SEED = 20260954;
export const P1_COUNTS = { dev: 48, val: 32, sealed: 64 } as const;
export const P1_SEALED_DIR = '/Users/ashkie/src/deevgames-wizards/sealed';

/** Used only by the one-time allocation command. Ordinary tests generate a
 * different small pool; they never regenerate or read this sealed allocation. */
export function buildP1Allocation() {
  const generated = generateOpenings({ count: 144, seed: P1_SEED, idPrefix: 'p1-', maxAttempts: 20000 });
  const pool = seededShuffle(generated.openings, P1_SEED);
  const strata = { dev: pool.slice(0, 48), val: pool.slice(48, 80), sealed: pool.slice(80) };
  validateOpenings(pool.map(o => o.spec));
  return { generated, strata };
}

function main(argv: readonly string[]): void {
  if (argv.length) throw new Error('split: P1 allocation parameters and destinations are frozen; no flags accepted');
  const outDir = path.dirname(fileURLToPath(import.meta.url));
  const sealedPath = path.join(P1_SEALED_DIR, 'p1-sealed.jsonl');
  const paths = { dev: path.join(outDir, 'p1-dev.jsonl'), val: path.join(outDir, 'p1-val.jsonl'), sealed: sealedPath };
  for (const dest of Object.values(paths)) if (fs.existsSync(dest)) throw new Error(`split: refuses to overwrite ${dest}`);
  const { generated, strata } = buildP1Allocation();
  fs.mkdirSync(P1_SEALED_DIR, { recursive: true, mode: 0o700 });
  const manifest = Object.entries(strata).map(([name, rows]) => {
    const text = renderOpeningSpecs(rows.map(o => o.spec));
    fs.writeFileSync(paths[name as keyof typeof paths], text, { flag: 'wx', mode: name === 'sealed' ? 0o600 : 0o644 });
    return { name, rows: rows.length, bytes: Buffer.byteLength(text), sha256: sha256(text) };
  });
  process.stdout.write(JSON.stringify({ rulesVersion: RULES_VERSION, seed: P1_SEED,
    bots: DRIVER_BOTS, attempts: generated.attempts, rejected: generated.rejected,
    plyDistribution: generated.plyDistribution, files: manifest }, null, 2) + '\n');
}

const invokedDirectly = process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) main(process.argv.slice(2));
