import { createHash } from 'node:crypto';
import { readFileSync, readdirSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../../', import.meta.url));
const collect = (path: string): string[] => readdirSync(path, { withFileTypes: true }).flatMap(e => e.isDirectory() ? collect(join(path, e.name)) : e.name.endsWith('.ts') ? [join(path, e.name)] : []);
const files = [...collect(join(root, 'src/game')), ...collect(join(root, 'server/explorer')), join(root, 'src/ai/simulate.ts'), join(root, 'server/observation.ts')].sort();
const hash = createHash('sha256');
for (const file of files) hash.update(relative(root, file)).update('\0').update(readFileSync(file)).update('\0');
export const EXPLORER_SOURCE_IDENTITY = { commit: process.env.RENDER_GIT_COMMIT ?? process.env.MUJU_SOURCE_REVISION ?? null, sha256: hash.digest('hex') };
