# Generated by Django 4.1.5 on 2023-01-27 19:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('item_type', models.CharField(choices=[('SEED', 'Seed'), ('SPROUT', 'Sprout'), ('CROP', 'Crop'), ('GIFT', 'Gift')], default='GIFT', max_length=6)),
                ('price', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('land_type', models.CharField(choices=[('FARM', 'Farm'), ('SHOP', 'Shop'), ('WILD', 'Wild'), ('HOME', 'Home')], default='WILD', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('location', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mythgarden.place')),
            ],
        ),
        migrations.CreateModel(
            name='Villager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='portraits/')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mythgarden.place')),
                ('surround', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='mythgarden.place')),
            ],
            bases=('mythgarden.place',),
        ),
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.session')),
                ('day', models.CharField(choices=[('SUN', 'Sun'), ('MON', 'Mon'), ('TUE', 'Tue'), ('WED', 'Wed'), ('THU', 'Thu'), ('FRI', 'Fri'), ('SAT', 'Sat')], default='SUN', max_length=9)),
                ('time', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(24.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.session')),
                ('name', models.CharField(default='Squall', max_length=255)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='portraits/')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.session')),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VillagerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villagers', to='mythgarden.place')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villager_states', to='mythgarden.session')),
                ('villager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='mythgarden.villager')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.ManyToManyField(blank=True, to='mythgarden.item')),
                ('occupants', models.ManyToManyField(blank=True, to='mythgarden.villager')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='mythgarden.place')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_states', to='mythgarden.session')),
            ],
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_1', models.CharField(choices=[('NORTH', 'North'), ('EAST', 'East'), ('SOUTH', 'South'), ('WEST', 'West')], max_length=5)),
                ('direction_2', models.CharField(choices=[('NORTH', 'North'), ('EAST', 'East'), ('SOUTH', 'South'), ('WEST', 'West')], max_length=5)),
                ('place_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_1', to='mythgarden.place')),
                ('place_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_2', to='mythgarden.place')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('TRAVEL', 'Travel'), ('TALK', 'Talk'), ('GIVE', 'Give'), ('PLANT', 'Plant'), ('WATER', 'Water'), ('HARVEST', 'Harvest'), ('BUY', 'Buy'), ('SELL', 'Sell')], max_length=7)),
                ('description', models.CharField(max_length=255)),
                ('cost_amount', models.IntegerField(default=1)),
                ('cost_unit', models.CharField(choices=[('MINUTE', 'm'), ('HOUR', 'h'), ('DAY', 'd'), ('KOIN', '₭')], max_length=6)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('secondary_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, choices=[('NORTH', 'North'), ('EAST', 'East'), ('SOUTH', 'South'), ('WEST', 'West')], max_length=5, null=True)),
                ('log_statement', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('secondary_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_content_type', to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='villager',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mythgarden.building'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.session')),
                ('items', models.ManyToManyField(blank=True, to='mythgarden.item')),
            ],
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['content_type', 'object_id'], name='mythgarden__content_5a9c98_idx'),
        ),
    ]
