# Generated by Django 4.1.5 on 2023-01-27 20:00

from django.db import migrations, models
import django.db.models.deletion
import mythgarden.models
import mythgarden.static_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='portrait',
            field=models.ImageField(default='portraits/squall-farmer.png', upload_to='portraits/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='places/idyllic-green-farm.png', upload_to='places/'),
        ),
        migrations.AlterField(
            model_name='session',
            name='key',
            field=models.CharField(default=mythgarden.static_helpers.generate_uuid, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.ForeignKey(default=mythgarden.models.place.Place.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mythgarden.place'),
        ),
    ]
