# Generated by Django 4.1.5 on 2023-01-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0002_alter_hero_portrait_alter_place_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('SHOP', 'Shop'), ('HOME', 'Home')], default='HOME', max_length=4),
        ),
        migrations.AlterField(
            model_name='place',
            name='land_type',
            field=models.CharField(choices=[('FARM', 'Farm'), ('WILD', 'Wild'), ('TOWN', 'Town')], default='WILD', max_length=4),
        ),
    ]
