# Generated by Django 4.1.5 on 2023-01-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0003_building_building_type_alter_place_land_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='skip_post_save_signal',
            field=models.BooleanField(default=False),
        ),
    ]
