# Generated by Django 4.1.5 on 2023-01-31 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0008_alter_action_cost_unit_alter_session_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='default_contents',
            field=models.ManyToManyField(blank=True, to='mythgarden.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='villager',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='mythgarden.building'),
        ),
    ]
