# Generated by Django 4.1.5 on 2023-01-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0009_place_default_contents_alter_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('COMMON', 'common'), ('UNCOMMON', 'uncommon'), ('RARE', 'rare'), ('EPIC', 'epic')], default='COMMON', max_length=8),
        ),
        migrations.AddField(
            model_name='place',
            name='item_pool',
            field=models.ManyToManyField(blank=True, related_name='pool_locations', to='mythgarden.item'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('TRAVEL', 'Travel'), ('TALK', 'Talk'), ('GIVE', 'Give'), ('PLANT', 'Plant'), ('WATER', 'Water'), ('HARVEST', 'Harvest'), ('BUY', 'Buy'), ('SELL', 'Sell'), ('GATHER', 'Gather')], max_length=7),
        ),
    ]
