# Generated by Django 4.1.5 on 2023-02-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0010_item_rarity_place_item_pool_alter_action_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('FARM', 'Farm'), ('MOUNTAIN', 'Mountain'), ('FOREST', 'Forest'), ('BEACH', 'Beach'), ('TOWN', 'Town'), ('SHOP', 'Shop'), ('HOME', 'Home')], default='TOWN', max_length=8),
        ),
    ]
