# Generated by Django 4.1.5 on 2023-02-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0012_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('SEED', 'Seed'), ('SPROUT', 'Sprout'), ('CROP', 'Crop'), ('GIFT', 'Gift'), ('FISH', 'Fish'), ('MINERAL', 'Mineral'), ('ARTIFACT', 'Artifact'), ('HERB', 'Herb'), ('FLOWER', 'Flower'), ('BERRY', 'Berry')], default='GIFT', max_length=8),
        ),
    ]
