# Generated by Django 4.1.5 on 2023-02-02 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0013_alter_item_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTypePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('SEED', 'Seed'), ('SPROUT', 'Sprout'), ('CROP', 'Crop'), ('GIFT', 'Gift'), ('FISH', 'Fish'), ('MINERAL', 'Mineral'), ('ARTIFACT', 'Artifact'), ('HERB', 'Herb'), ('FLOWER', 'Flower'), ('BERRY', 'Berry')], max_length=8)),
                ('valence', models.CharField(choices=[('LOVE', 'love'), ('LIKE', 'like'), ('NEUTRAL', 'neutral'), ('DISLIKE', 'dislike'), ('HATE', 'hate')], default='NEUTRAL', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='cost_unit',
            field=models.CharField(choices=[('MINUTE', 'min'), ('HOUR', 'hr'), ('DAY', 'day'), ('KOIN', '₭')], max_length=6),
        ),
        migrations.AlterField(
            model_name='villagerstate',
            name='affinity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='villager',
            name='item_type_preferences',
            field=models.ManyToManyField(blank=True, related_name='preferred_by', to='mythgarden.itemtypepreference'),
        ),
    ]
