# Generated by Django 4.1.5 on 2023-02-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0014_itemtypepreference_alter_action_cost_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='cost_unit',
            field=models.CharField(choices=[('MINUTE', 'min'), ('HOUR', 'hr'), ('DAY', 'day'), ('KOIN', '⚜️')], max_length=6),
        ),
    ]
