# Generated by Django 4.1.5 on 2023-02-03 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0015_alter_action_cost_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1439)]),
        ),
    ]
