# Generated by Django 4.1.5 on 2023-02-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0016_alter_clock_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='villager',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
