# Generated by Django 4.1.5 on 2023-02-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0017_villager_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villager',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
