# Generated by Django 4.1.5 on 2023-02-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0018_alter_villager_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('TRAVEL', 'Travel'), ('TALK', 'Talk'), ('GIVE', 'Give'), ('PLANT', 'Plant'), ('WATER', 'Water'), ('HARVEST', 'Harvest'), ('BUY', 'Buy'), ('SELL', 'Sell'), ('GATHER', 'Gather'), ('SLEEP', 'Sleep')], max_length=7),
        ),
    ]
