# Generated by Django 4.1.5 on 2023-02-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0019_alter_action_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='cost_unit',
            field=models.CharField(choices=[('MINUTE', 'min'), ('HOUR', 'hr'), ('KOIN', '⚜️')], max_length=6),
        ),
    ]
