# Generated by Django 4.1.5 on 2023-02-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0021_clock_is_new_day_villagerstate_has_been_given_gift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_been_watered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='mythgarden.item')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_tokens', to='mythgarden.session')),
            ],
        ),
        migrations.RenameField(
            model_name='place',
            old_name='default_contents',
            new_name='default_items',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='items',
        ),
        migrations.RemoveField(
            model_name='placestate',
            name='contents',
        ),
        migrations.DeleteModel(
            name='ItemState',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_tokens',
            field=models.ManyToManyField(blank=True, to='mythgarden.itemtoken'),
        ),
        migrations.AddField(
            model_name='placestate',
            name='item_tokens',
            field=models.ManyToManyField(blank=True, to='mythgarden.itemtoken'),
        ),
    ]
