# Generated by Django 4.1.5 on 2023-02-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0022_itemtoken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villagerstate',
            name='has_been_greeted',
        ),
        migrations.AddField(
            model_name='villagerstate',
            name='has_been_talked_to',
            field=models.BooleanField(default=False),
        ),
    ]
