# Generated by Django 4.1.5 on 2023-02-06 22:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0023_remove_villagerstate_has_been_greeted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SUN', 'Sun'), ('MON', 'Mon'), ('TUE', 'Tue'), ('WED', 'Wed'), ('THU', 'Thu'), ('FRI', 'Fri'), ('SAT', 'Sat')], default='SUN', max_length=9)),
                ('time', models.IntegerField(default=360, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1439)])),
                ('event_type', models.CharField(choices=[('ITEMS_APPEAR', 'Items appear')], default='ITEMS_APPEAR', max_length=12)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('items', models.ManyToManyField(blank=True, related_name='scheduled_events', to='mythgarden.item')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_events', to='mythgarden.place')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledEventState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_occurred', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='mythgarden.scheduledevent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_event_states', to='mythgarden.session')),
            ],
        ),
    ]
