# Generated by Django 4.1.5 on 2023-02-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0024_scheduledevent_scheduledeventstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledevent',
            name='description',
        ),
    ]
