# Generated by Django 4.1.5 on 2023-02-06 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0025_remove_scheduledevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hearts_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='koin_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clock',
            name='time',
            field=models.IntegerField(default=360, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1439)]),
        ),
    ]
