# Generated by Django 4.1.5 on 2023-02-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0026_hero_hearts_earned_hero_koin_earned_alter_clock_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='is_in_bed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
