# Generated by Django 4.1.5 on 2023-02-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0027_hero_is_in_bed_session_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='game_over',
            field=models.BooleanField(default=True),
        ),
    ]
