# Generated by Django 4.1.5 on 2023-02-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0028_session_game_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagerstate',
            name='has_ever_been_talked_to',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DialogueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity_tier', models.IntegerField(blank=True, null=True)),
                ('trigger', models.CharField(choices=[('LOVED_GIFT', 'Loved Gift'), ('LIKED_GIFT', 'Liked Gift'), ('NEUTRAL_GIFT', 'Neutral Gift'), ('DISLIKED_GIFT', 'Disliked Gift'), ('HATED_GIFT', 'Hated Gift'), ('FIRST_MEETING', 'First Meeting'), ('TALKED_TO', 'Talked To')], default='TALKED_TO', max_length=13)),
                ('full_text', models.TextField()),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_lines', to='mythgarden.villager')),
            ],
        ),
    ]
