# Generated by Django 4.1.5 on 2023-03-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0030_alter_villager_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='message',
        ),
        migrations.AddField(
            model_name='session',
            name='initial_message_text',
            field=models.CharField(default='Welcome to Mythgarden! You have one week to grow crops, make friends, and find treasures. Good luck and have fun!', max_length=255),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mythgarden.session')),
            ],
        ),
    ]
