# Generated by Django 4.1.5 on 2023-02-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0030_alter_villager_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='portrait',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.RemoveField(
            model_name='villager',
            name='portrait',
        ),
        migrations.AddField(
            model_name='hero',
            name='image_path',
            field=models.CharField(default='portraits/squall-farmer.png', max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='image_path',
            field=models.CharField(default='places/idyllic-green-farm.png', max_length=255),
        ),
        migrations.AddField(
            model_name='villager',
            name='image_path',
            field=models.CharField(blank=True, default='portraits/squall-farmer.png', max_length=255, null=True),
        ),
    ]
