# Generated by Django 4.1.5 on 2023-03-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0031_remove_hero_portrait_remove_place_image_and_more'),
        ('mythgarden', '0031_remove_session_message_session_initial_message_text_and_more'),
    ]

    operations = [
    ]
