# Generated by Django 4.1.5 on 2023-03-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0032_merge_20230304_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
    ]
