# Generated by Django 4.1.5 on 2023-03-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0033_message_is_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='target_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mythgarden.itemtoken'),
        ),
        migrations.AddField(
            model_name='action',
            name='target_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mythgarden.place'),
        ),
        migrations.AddField(
            model_name='action',
            name='target_villager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mythgarden.villager'),
        ),
    ]
