# Generated by Django 4.1.5 on 2023-03-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0034_action_target_item_action_target_place_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='action',
            name='mythgarden__content_5a9c98_idx',
        ),
        migrations.RemoveField(
            model_name='action',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='action',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='action',
            name='secondary_content_type',
        ),
        migrations.RemoveField(
            model_name='action',
            name='secondary_object_id',
        ),
    ]
