# Generated by Django 4.1.5 on 2023-03-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0035_remove_action_mythgarden__content_5a9c98_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image_path',
            field=models.CharField(default='portraits/default.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(default='New Farmer', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='image_path',
            field=models.CharField(default='places/farm-unsplash.jpeg', max_length=255),
        ),
        migrations.AlterField(
            model_name='villager',
            name='image_path',
            field=models.CharField(blank=True, default='portraits/default.png', max_length=255, null=True),
        ),
    ]
