# Generated by Django 4.1.5 on 2023-03-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0036_alter_hero_image_path_alter_hero_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='HeroState',
        ),
    ]
