# Generated by Django 4.1.5 on 2023-03-15 21:00

from django.db import migrations, models
import django.db.models.deletion
import mythgarden.models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0037_rename_hero_herostate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Farmer', max_length=255)),
                ('image_path', models.CharField(default='portraits/default.png', max_length=255)),
                ('high_score', models.IntegerField(default=0)),
                ('boost_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='herostate',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='herostate',
            name='name',
        ),
        migrations.AddField(
            model_name='herostate',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, null=True, related_name='states', to='mythgarden.hero'),
            preserve_default=False,
        ),
    ]
