# Generated by Django 4.1.5 on 2023-03-15 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0040_alter_hero_current_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='current_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero', to='mythgarden.session'),
        ),
    ]
