# Generated by Django 4.1.5 on 2023-03-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0041_alter_hero_current_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hero', to='mythgarden.session'),
        ),
        migrations.AlterField(
            model_name='herostate',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hero_state', serialize=False, to='mythgarden.session'),
        ),
    ]
