# Generated by Django 4.1.5 on 2023-03-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0044_alter_session_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtoken',
            name='bought_from_store',
            field=models.BooleanField(default=False),
        ),
    ]
