# Generated by Django 4.1.5 on 2023-03-20 16:19

from django.db import migrations, models
import django.db.models.deletion
import mythgarden.models.hero


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0045_itemtoken_bought_from_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herostate',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mythgarden.hero', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_session', to='mythgarden.hero', null=True),
        ),
    ]
