# Generated by Django 4.1.5 on 2023-03-25 22:37

from django.db import migrations, models
import django.db.models.deletion
import mythgarden.models.place


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0048_alter_herostate_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch_slot_type', models.CharField(choices=[('MINOR', 'minor'), ('MEDIUM', 'medium'), ('MAJOR', 'major'), ('GRAND', 'grand')], max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduledevent',
            name='items',
        ),
        migrations.RemoveField(
            model_name='scheduledevent',
            name='place',
        ),
        migrations.AddField(
            model_name='itemtoken',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='is_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clock',
            name='day',
            field=models.CharField(choices=[('MON', 'Mon'), ('TUE', 'Tue'), ('WED', 'Wed'), ('THU', 'Thu'), ('FRI', 'Fri'), ('SAT', 'Sat'), ('SUN', 'Sun')], default='MON', max_length=9),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('SEED', 'Seed'), ('SPROUT', 'Sprout'), ('CROP', 'Crop'), ('GIFT', 'Gift'), ('FISH', 'Fish'), ('MINERAL', 'Mineral'), ('FOSSIL', 'Fossil'), ('TECHNO', 'Techno'), ('MAGIC', 'Magic'), ('HERB', 'Herb'), ('FLOWER', 'Flower'), ('BERRY', 'Berry')], default='GIFT', max_length=8),
        ),
        migrations.AlterField(
            model_name='itemtypepreference',
            name='item_type',
            field=models.CharField(choices=[('SEED', 'Seed'), ('SPROUT', 'Sprout'), ('CROP', 'Crop'), ('GIFT', 'Gift'), ('FISH', 'Fish'), ('MINERAL', 'Mineral'), ('FOSSIL', 'Fossil'), ('TECHNO', 'Techno'), ('MAGIC', 'Magic'), ('HERB', 'Herb'), ('FLOWER', 'Flower'), ('BERRY', 'Berry')], max_length=8),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='day',
            field=models.CharField(choices=[('MON', 'Mon'), ('TUE', 'Tue'), ('WED', 'Wed'), ('THU', 'Thu'), ('FRI', 'Fri'), ('SAT', 'Sat'), ('SUN', 'Sun')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='event_type',
            field=models.CharField(choices=[('SHOP_POPULATES', 'Shop populates'), ('VILLAGER_APPEARS', 'Villager appears')], max_length=16),
        ),
        migrations.CreateModel(
            name='PopulateShopEvent',
            fields=[
                ('scheduledevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mythgarden.scheduledevent')),
                ('gift_quantity', models.IntegerField(blank=True, null=True)),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_shop_event', to='mythgarden.item')),
                ('merch_slots', models.ManyToManyField(blank=True, to='mythgarden.merchslot')),
                ('seed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seed_shop_event', to='mythgarden.item')),
                ('shop', models.ForeignKey(default=mythgarden.models.place.Place.get_default_shop_pk, on_delete=django.db.models.deletion.CASCADE, to='mythgarden.place')),
            ],
            bases=('mythgarden.scheduledevent',),
        ),
        migrations.CreateModel(
            name='VillagerAppearsEvent',
            fields=[
                ('scheduledevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mythgarden.scheduledevent')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mythgarden.place')),
                ('villager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mythgarden.villager')),
            ],
            bases=('mythgarden.scheduledevent',),
        ),
    ]
