# Generated by Django 4.1.5 on 2023-03-25 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0049_merchslot_remove_scheduledevent_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagerstate',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villagers', to='mythgarden.place'),
        ),
    ]
