# Generated by Django 4.1.5 on 2023-03-26 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0051_alter_villagerstate_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='default_items',
        ),
        migrations.RemoveField(
            model_name='placestate',
            name='occupants',
        ),
        migrations.RemoveField(
            model_name='villagerstate',
            name='location',
        ),
        migrations.AddField(
            model_name='villagerstate',
            name='location_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants', to='mythgarden.placestate'),
        ),
    ]
