# Generated by Django 4.1.5 on 2023-03-28 19:37

from django.db import migrations, models
import django.db.models.deletion
import mythgarden.models.farmer_portrait


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0052_remove_place_default_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerPortrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(default='default.png', max_length=255, unique=True)),
            ],
            options={
                'ordering': ['image_path'],
            },
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='itemtoken',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='villager',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='villagerstate',
            options={'ordering': ['villager__name']},
        ),
        migrations.RemoveField(
            model_name='hero',
            name='image_path',
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(default='New Farmer', max_length=16),
        ),
        migrations.AlterField(
            model_name='place',
            name='image_path',
            field=models.CharField(default='farm-unsplash.jpeg', max_length=255),
        ),
        migrations.AlterField(
            model_name='villager',
            name='image_path',
            field=models.CharField(blank=True, default='default.png', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='portrait',
            field=models.ForeignKey(default=mythgarden.models.farmer_portrait.FarmerPortrait.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='mythgarden.farmerportrait'),
        ),
    ]
