# Generated by Django 4.1.5 on 2023-03-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0053_farmerportrait_alter_building_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='has_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('TRAVEL', 'Travel'), ('TALK', 'Talk'), ('GIVE', 'Give'), ('PLANT', 'Plant'), ('WATER', 'Water'), ('HARVEST', 'Harvest'), ('BUY', 'Buy'), ('SELL', 'Sell'), ('PUT', 'Put'), ('TAKE', 'Take'), ('GATHER', 'Gather'), ('SLEEP', 'Sleep')], max_length=7),
        ),
        migrations.AlterField(
            model_name='action',
            name='cost_amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='cost_unit',
            field=models.CharField(blank=True, choices=[('MINUTE', 'min'), ('HOUR', 'hr'), ('KOIN', '⚜️')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='initial_message_text',
            field=models.CharField(default='Welcome to Mythgarden! You have one week to grow crops, make friends, and find treasures. Ooh and you can pick an avatar and change your name if you want! Good luck and have fun!', max_length=255),
        ),
    ]
