# Generated by Django 4.1.5 on 2023-04-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0058_action_cost_wait_class_alter_action_cost_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='luck_level',
            field=models.IntegerField(default=0),
        ),
    ]
