# Generated by Django 4.1.5 on 2023-04-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0059_hero_luck_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='fresh',
            field=models.JSONField(default=dict),
        ),
    ]
