# Generated by Django 4.1.5 on 2023-04-11 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0060_session_fresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_dialogue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mythgarden.dialogueline'),
        ),
    ]
