# Generated by Django 4.1.5 on 2023-04-11 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0061_session_current_dialogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='last_triggered_day',
            field=models.CharField(choices=[('MON', 'Mon'), ('TUE', 'Tue'), ('WED', 'Wed'), ('THU', 'Thu'), ('FRI', 'Fri'), ('SAT', 'Sat'), ('SUN', 'Sun')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='clock',
            name='last_triggered_time',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1439)]),
        ),
    ]
