# Generated by Django 4.1.5 on 2023-04-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0063_alter_clock_last_triggered_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='fresh',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='ScheduledEventState',
        ),
    ]
