# Generated by Django 4.1.5 on 2023-04-11 23:46

from django.db import migrations, models
import django.db.models.deletion
import mythgarden.models.place


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0064_alter_session_fresh_delete_scheduledeventstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.ForeignKey(default=mythgarden.models.place.Place.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mythgarden.place'),
        ),
    ]
