# Generated by Django 4.1.5 on 2023-04-13 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0067_rename_has_ever_been_talked_to_villagerstate_has_ever_been_interacted_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='closing_time',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1439)]),
        ),
        migrations.AddField(
            model_name='building',
            name='opening_time',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1439)]),
        ),
        migrations.AddField(
            model_name='item',
            name='effort_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='growth_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtoken',
            name='days_growing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='cost_wait_class',
            field=models.CharField(blank=True, choices=[('TRIVIAL', 'trivial'), ('TRIVIAL_PLUS', 'trivialPlus'), ('TRIVIAL_PLUS_PLUS', 'trivialPlusPlus'), ('SMALL_MINUS', 'smallMinus'), ('SMALLISH', 'smallish'), ('SMALL', 'small'), ('SMALL_PLUS', 'smallPlus'), ('SMALL_PLUS_PLUS', 'smallPlusPlus'), ('MEDIUM_MINUS', 'mediumMinus'), ('MEDIUM', 'medium'), ('MEDIUM_PLUS', 'mediumPlus'), ('LONG_MINUS', 'longMinus'), ('LONG', 'long')], max_length=17, null=True),
        ),
    ]
