# Generated by Django 4.1.5 on 2023-04-21 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0070_achievement_mythegg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledevent',
            name='day',
            field=models.CharField(blank=True, choices=[('MON', 'Mon'), ('TUE', 'Tue'), ('WED', 'Wed'), ('THU', 'Thu'), ('FRI', 'Fri'), ('SAT', 'Sat'), ('SUN', 'Sun')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='current_dialogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mythgarden.dialogueline'),
        ),
    ]
