# Generated by Django 4.1.5 on 2023-04-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0071_alter_scheduledevent_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mythlingstate',
            name='is_in_possession',
            field=models.BooleanField(default=False),
        ),
    ]
