# Generated by Django 4.1.5 on 2026-01-02 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0073_alter_clock_day_alter_clock_last_triggered_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villagers_move', models.BooleanField(default=False)),
                ('building_hours', models.BooleanField(default=False)),
                ('advanced_crops', models.BooleanField(default=False)),
                ('dynamic_shop', models.BooleanField(default=False)),
                ('draft_villagers_move', models.BooleanField(default=False)),
                ('draft_building_hours', models.BooleanField(default=False)),
                ('draft_advanced_crops', models.BooleanField(default=False)),
                ('draft_dynamic_shop', models.BooleanField(default=False)),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='mythgarden.hero')),
            ],
        ),
    ]
