# Generated by Django 4.1.5 on 2026-01-02 20:00

from django.db import migrations


def populate_game_settings(apps, schema_editor):
    """Create GameSettings for all existing Heroes."""
    Hero = apps.get_model('mythgarden', 'Hero')
    GameSettings = apps.get_model('mythgarden', 'GameSettings')

    for hero in Hero.objects.all():
        if not hasattr(hero, 'settings'):
            GameSettings.objects.create(hero=hero)


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0074_gamesettings'),
    ]

    operations = [
        migrations.RunPython(populate_game_settings, migrations.RunPython.noop),
    ]
