# Generated by Django 4.1.5 on 2026-01-02 21:00
# No-op: plant seed Items are loaded via fixtures (initial_data.json)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0075_populate_game_settings'),
    ]

    operations = []
