import { useEffect, useState } from 'react'

// manifest.json maps an image slug -> the actual filename in /assets.
// It is generated by scripts/fetch-images.mjs. If it's missing (images not
// fetched yet) or a slug isn't present, we show a clean labeled placeholder.
let manifestCache = null
let manifestPromise = null

function loadManifest() {
  if (manifestCache) return Promise.resolve(manifestCache)
  if (!manifestPromise) {
    manifestPromise = fetch('/assets/manifest.json')
      .then((r) => (r.ok ? r.json() : {}))
      .then((m) => (manifestCache = m))
      .catch(() => (manifestCache = {}))
  }
  return manifestPromise
}

export default function ItemImage({ slug, label, size = 220 }) {
  const [file, setFile] = useState(undefined) // undefined=loading, null=none, string=ok
  const [errored, setErrored] = useState(false)

  useEffect(() => {
    let alive = true
    if (!slug) {
      setFile(null)
      return
    }
    setErrored(false)
    loadManifest().then((m) => {
      if (alive) setFile(m[slug] || null)
    })
    return () => {
      alive = false
    }
  }, [slug])

  const showPlaceholder = file === null || errored
  const style = { width: size, height: size }

  if (showPlaceholder) {
    return (
      <div className="item-img placeholder" style={style} aria-label={label}>
        <span>{label}</span>
      </div>
    )
  }
  if (file === undefined) {
    return <div className="item-img loading" style={style} />
  }
  return (
    <div className="item-img" style={style}>
      <img
        src={'/assets/' + file}
        alt={label}
        onError={() => setErrored(true)}
        draggable={false}
      />
    </div>
  )
}
