import { expect, test } from '@playwright/test';
for (const width of [1280, 390]) test(`explorer setup, independent forecasts, controls and reload at ${width}px`, async ({ page, request }, info) => {
  await page.setViewportSize({ width, height: 1000 });
  await page.goto('/muju/explorer');
  await expect(page.getByRole('heading', { name: 'Advantage exhaustion explorer' })).toBeVisible();
  const handicap = page.getByRole('combobox', { name: 'Black crystal handicap' });
  await expect(handicap).toHaveValue('9.5');
  expect(await handicap.locator('option').allTextContents()).toHaveLength(19);
  await page.getByRole('button', { name: 'Create experiment', exact: true }).click();
  await expect(page.getByText('Waiting for runner', { exact: true })).toBeVisible();
  const id = new URL(page.url()).searchParams.get('experiment')!;
  const token = await page.evaluate(id => localStorage.getItem(`muju-explorer:${location.origin}:${id}`), id);
  const headers = { Authorization: `Bearer ${token}` }, base = `/api/muju/experiments/${id}`;
  const claim = async () => { const response = await request.post(`${base}/claim`, { headers, data: { workerId: 'browser-smoke' } }); expect(response.ok()).toBeTruthy(); return (await response.json()).job; };
  let job = await claim();
  const assessment = (p: number) => ({ kind: 'assess', assessment: { whiteWin: p, pressure: 'balanced', counterplay: 'Both sides have active choices.', explanation: 'No opening domination.' }, memory: '' });
  await request.post(`${base}/submit`, { headers, data: { jobId: job.id, input: assessment(0.57) } });
  expect((await (await request.get(base)).json()).checkpoints[0].assessments).toEqual({});
  job = await claim();
  await request.post(`${base}/submit`, { headers, data: { jobId: job.id, input: assessment(0.48) } });
  await expect(page.getByText('57% White · balanced', { exact: true })).toBeVisible();
  await expect(page.getByText('48% White · balanced', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Resume experiment' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Resume experiment' })).toBeVisible();
  await page.getByLabel('Handicap judgment').fill('Both sides had meaningful choices.');
  await page.getByRole('button', { name: 'Save judgment' }).click();
  await expect(page.locator('blockquote')).toHaveText('Both sides had meaningful choices.');
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Export evidence' }).click()]);
  expect(download.suggestedFilename()).toContain(id);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: info.outputPath(`explorer-${width}.png`), fullPage: true });
});
